config/routes.rb
Rails.application.routes.draw do

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  root 'tasks#show'

  resources :users
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    if current_user
      @todos = @current_user.tasks
    end 
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      render json: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    render json: @task
    @task.destroy
  end

  def update
    @task = Task.find(params[:id])
    if @task.done == false
      @task.update_attributes(done: true)
    else
      @task.update_attributes(done: false)
    end
    render json: @task
  end

  private
    def task_params
      params.require(:task).permit(:description, :done)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password,:firstname,:lastname,:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user = User.where(id: session[:user_id]).first if session[:user_id]
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoreact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>

<header>
  <%if !session[:user_id].nil?%>
    <p><%= link_to 'Logout', logout_path %></p>
  <%else%>
    <p><%= link_to 'Login', login_path %> or <%= link_to 'Sign up', signup_path %> to start using todos! </p>
  <%end%>
</header>

<body>
  <%= yield %>
</body>
</html>

app/views/tasks/show.html.erb
<div id="page-container">
  <div class="page-header">
    <h1>todos!</h1>
  </div>
    <% if !session[:user_id].nil? %>
      <%= react_component 'TodoApp', todos: @todos %>    
    <%end%>
</div>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

  <%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :firstname %>

    <%= f.label :last_name %>
    <%= f.text_field :lastname %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit %>
  <%end%>